{
 "title": "Dashing",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU load",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests duration Продолжительность запросов",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибки 4xx/5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4xx|5xx\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Series Запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests Кол-во запросов",
   "type": "stat",
   "description": "2xx/2xx/4xx",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total{}", "legendFormat": "__auto" }
   ]
  }
 ]
}