FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY services/ml_service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt


COPY services/ml_service /app/services/ml_service
COPY services/models /app/services/models

EXPOSE 8000

CMD ["sh", "-c", "uvicorn services.ml_service.main:app --host 0.0.0.0 --port ${APP_PORT:-8000}"]
