FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# requirements теперь относительно build context = services/
COPY ml_service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# код сервиса и модель тоже относительно services/
COPY ml_service /app/services/ml_service
COPY models /app/services/models

EXPOSE 8000

CMD ["sh", "-c", "uvicorn services.ml_service.main:app --host 0.0.0.0 --port ${APP_PORT:-8000}"]
