services:
  ml_service:
    build:
      context: .
      dockerfile: Dockerfile_ml_service
    env_file:
      - .env
    ports:
      - "8002:8000"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - ml_service
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
